"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os
directory = os.getcwd()

APP = ['magic_gui.py']
DATA_FILES = [('', ['help_files', 'data_model', 'documentation', 'images'])]
OPTIONS = {'argv_emulation': False,
           'iconfile': os.path.join(directory, 'images', 'text_x_xslfo.icns')}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
